32. Используя модуль array и библиотеку numpy, решить следующие задачи:
а) Дан массив размера  N . После каждого отрицательного элемента массива вставить элемент с нулевым значением.
б) Дана матрица размера  M×N . Упорядочить ее столбцы так, чтобы их последние элементы образовывали убывающую последовательность.

In [ ]:
import numpy as np

# а) Дан массив размера N. После каждого отрицательного элемента массива вставить элемент с нулевым значением.
def insert_zero_after_negative(arr):
    arr = np.array(arr)
    neg_indices = np.where(arr < 0)[0]
    result = np.insert(arr, neg_indices + 1, 0)
    return result

# Пример использования
arr_a = [1, -2, 3, 4, -5, 6]
result_a = insert_zero_after_negative(arr_a)
print(result_a)

# б) Дана матрица размера M×N. Упорядочить ее столбцы так, чтобы их последние элементы образовывали убывающую последовательность.
def sort_columns_by_last_element(matrix):
    matrix = np.array(matrix)
    last_elements = matrix[:, -1]
    sorted_indices = np.argsort(last_elements)[::-1]
    result = matrix[:, sorted_indices]
    return result

# Пример использования
mat_b = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
result_b = sort_columns_by_last_element(mat_b)
print(result_b)

[ 1 -2  0  3  4 -5  0  6]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


33. Дан стек. Необходимо найти среднее арифметическое всех его элементов.

In [ ]:
stack = [1, 2, 3, 4, 5]  # пример стека

total = 0
count = 0

while stack:
    total += stack.pop()
    count += 1

average = total / count
print("Среднее арифметическое всех элементов стека:", average)


Среднее арифметическое всех элементов стека: 3.0


In [ ]:
def найти_среднее_арифметическое(стек):
    сумма = 0
    количество_элементов = 0

    while not стек.пустой():
        элемент = стек.удалить_верхний()

        if isinstance(элемент, (int, float)):
            сумма += элемент
            количество_элементов += 1

    if количество_элементов > 0:
        return сумма / количество_элементов
    else:
        return "Стек пустой, невозможно найти среднее арифметическое"


34. Создать класс очереди, который будет поддерживать операции добавления элемента в конец очереди и удаления элемента из середины очереди по значению.

In [ ]:
class Queue:
    def __init__(self):
        self.queue = []

    def add_to_end(self, value):
        self.queue.append(value)

    def remove_by_value(self, value):
        if value in self.queue:
            self.queue.remove(value)
        else:
            print("Element not found in queue")

    def display_queue(self):
        print(self.queue)


# Пример использования
q = Queue()
q.add_to_end(1)
q.add_to_end(2)
q.add_to_end(3)
q.add_to_end(4)
q.display_queue()

q.remove_by_value(2)
q.display_queue()

[1, 2, 3, 4]
[1, 3, 4]


35. Создайте двусвязный список для хранения информации о студентах в университете. Каждый элемент списка должен содержать имя, фамилию, номер группы, список предметов, которые студент изучает, и оценки по каждому предмету.

In [ ]:
class Node: #класс для создания узла списка, который содержит информацию о студенте
    def __init__(self, first_name, last_name, group_number, subjects=None, grades=None):
        self.first_name = first_name
        self.last_name = last_name
        self.group_number = group_number
        self.subjects = subjects if subjects else []
        self.grades = grades if grades else []
        self.prev = None
        self.next = None

class DoublyLinkedList: #класс для создания двусвязного списка студентов
    def __init__(self):
        self.head = None

    def add_student(self, first_name, last_name, group_number, subjects=None, grades=None): # метод для добавления нового студента в список
        new_student = Node(first_name, last_name, group_number, subjects, grades)
        if not self.head:
            self.head = new_student
        else:
            current = self.head
            while current.next:
                current = current.next
            current.next = new_student
            new_student.prev = current

    def display_students(self): #
        current = self.head
        while current:
            print(f"Name: {current.first_name} {current.last_name}, Group: {current.group_number}")
            if current.subjects:
                for i in range(len(current.subjects)):
                    print(f"Subject: {current.subjects[i]}, Grade: {current.grades[i]}")
            current = current.next

# Пример
university = DoublyLinkedList()
university.add_student("John", "Doe", "A123", ["Math", "Physics"], [85, 90])
university.add_student("Jane", "Smith", "B456", ["Chemistry", "Biology"], [75, 80])

university.display_students()

Name: John Doe, Group: A123
Subject: Math, Grade: 85
Subject: Physics, Grade: 90
Name: Jane Smith, Group: B456
Subject: Chemistry, Grade: 75
Subject: Biology, Grade: 80


In [ ]:
class Node:
    def __init__(self, name, surname, group_number, subjects, grades):
        self.name = name
        self.surname = surname
        self.group_number = group_number
        self.subjects = subjects if subjects is not None else []
        self.grades = grades if grades is not None else []
        self.prev = None
        self.next = None


class DoublyLinkedList:
    def __init__(self):
        self.head = None
        self.tail = None

    def append(self, name=None, surname=None, group_number=None, subjects=None, grades=None):
        new_node = Node(name, surname, group_number, subjects, grades)
        if self.head is None:
            self.head = new_node
            self.tail = new_node
        else:
            new_node.prev = self.tail
            self.tail.next = new_node
            self.tail = new_node

    def display_list(self):
        current = self.head
        while current:
            print("Name:", current.name)
            print("Surname:", current.surname)
            print("Group Number:", current.group_number)
            print("Subjects:", current.subjects)
            print("Grades:", current.grades)
            print()
            current = current.next


# Пример использования
students_list = DoublyLinkedList()
students_list.append("Alice", "Smith", "Group 1", ["Math", "Physics"], [85, 90])
students_list.append("Bob", "Johnson", "Group 2", ["Chemistry", "Biology"], [78, 82])
students_list.display_list()


Name: Alice
Surname: Smith
Group Number: Group 1
Subjects: ['Math', 'Physics']
Grades: [85, 90]

Name: Bob
Surname: Johnson
Group Number: Group 2
Subjects: ['Chemistry', 'Biology']
Grades: [78, 82]



36. Реализовать функцию, которая находит среднее арифметическое всех элементов двусвязного списка.

In [ ]:
class Node:
    def __init__(self, data):
        self.data = data
        self.prev = None
        self.next = None

class DoublyLinkedList:
    def __init__(self):
        self.head = None

    def add_node(self, data):
        new_node = Node(data)
        if self.head is None:
            self.head = new_node
        else:
            current = self.head
            while current.next:
                current = current.next
            current.next = new_node
            new_node.prev = current

    def calculate_average(self):
        total = 0
        count = 0
        current = self.head
        while current:
            total += current.data
            count += 1
            current = current.next

        if count == 0:
            return 0
        else:
            return total / count

# Пример использования
dll = DoublyLinkedList()
dll.add_node(10)
dll.add_node(20)
dll.add_node(30)

average = dll.calculate_average()
print("Среднее арифметическое всех элементов двусвязного списка:", average)


Среднее арифметическое всех элементов двусвязного списка: 20.0


In [ ]:
class Node:
    def __init__(self, value=None):
        self.value = value
        self.prev = None
        self.next = None


class DoublyLinkedList:
    def __init__(self):
        self.head = None
        self.tail = None

    def append(self, value):
        new_node = Node(value)
        if self.head is None:
            self.head = new_node
            self.tail = new_node
        else:
            new_node.prev = self.tail
            self.tail.next = new_node
            self.tail = new_node

    def display_list(self):
        current = self.head
        while current:
            print(current.value)
            current = current.next

    def find_average(self):
        current = self.head
        sum_values = 0
        count = 0
        while current:
            sum_values += current.value
            count += 1
            current = current.next
        if count == 0:
            return 0
        return sum_values / count


# Пример использования
my_list = DoublyLinkedList()
my_list.append(10)
my_list.append(20)
my_list.append(30)

print("Doubly Linked List:")
my_list.display_list()

average = my_list.find_average()
print("Average of the elements:", average)


Doubly Linked List:
10
20
30
Average of the elements: 20.0


37. Реализовать функцию, которая удаляет все повторяющиеся элементы из циклического двусвязного списка.

In [ ]:
class Node:
    def __init__(self, value=None):
        self.value = value
        self.prev = None
        self.next = None


class DoublyLinkedList:
    def __init__(self):
        self.head = None
        self.tail = None

    def append(self, value):
        new_node = Node(value)
        if self.head is None:
            self.head = new_node
            self.tail = new_node
        else:
            new_node.prev = self.tail
            self.tail.next = new_node
            self.tail = new_node

    def display_list(self):
        current = self.head
        while current:
            print(current.value)
            current = current.next

    def remove_duplicates(self):
        current_node = self.head
        while current_node:
            runner = current_node.next
            while runner:
                if current_node.value == runner.value:
                    runner.prev.next = runner.next
                    if runner.next:
                        runner.next.prev = runner.prev
                runner = runner.next
            current_node = current_node.next


# Пример использования
my_list = DoublyLinkedList()
my_list.append(10)
my_list.append(20)
my_list.append(10)
my_list.append(30)
my_list.append(20)
my_list.append(30)

print("Original Doubly Linked List:")
my_list.display_list()

my_list.remove_duplicates()

print("\nList after removing duplicates:")
my_list.display_list()


Original Doubly Linked List:
10
20
10
30
20
30

List after removing duplicates:
10
20
30


41
а) Создать класс «Продукт» с полями «Название», «Цена», «Количество» и «Срок годности». Создать хеш-таблицу для хранения объектов класса «Продукт» по ключу — названию продукта.
б) Написать функцию для нахождения наиболее часто встречающегося ключа в хеш-таблице.
в) Реализуйте хеш-таблицу для хранения информации о заказах в ресторане. Ключом является номер заказа, значение — объект, содержащий информацию о заказе (список блюд, стоимость заказа, адрес доставки и т.д.). Используйте метод разрешения коллизий методом цепочек и реализуйте возможность поиска элементов в таблице.

In [ ]:
class Product:
    def __init__(self, name, price, quantity, expiry_date):
        self.name = name
        self.price = price
        self.quantity = quantity
        self.expiry_date = expiry_date

class ProductHashTable:
    def __init__(self):
        self.table = {}

    def add_product(self, product):
        self.table[product.name] = product

    def find_product(self, product_name):
        if product_name in self.table:
            return self.table[product_name]
        else:
            return None

# Пример:
product_table = ProductHashTable()

product1 = Product("Яблоки", 2.5, 10, "01.01.2022")
product2 = Product("Молоко", 1.5, 5, "05.01.2022")

product_table.add_product(product1)
product_table.add_product(product2)

found_product = product_table.find_product("Яблоки")
if found_product:
    print("Информация о продукте:", found_product.name, found_product.price, found_product.quantity, found_product.expiry_date)
else:
    print("Продукт не найден.")

Информация о продукте: Яблоки 2.5 10 01.01.2022


In [ ]:
class Product:
    def __init__(self, name, price, quantity, expiry_date):
        self.name = name
        self.price = price
        self.quantity = quantity
        self.expiry_date = expiry_date

product_table = {}

def add_product_to_table(product):
    product_table[product.name] = product

# Пример использования:
product1 = Product("Яблоки", 2.5, 10, "01.01.2022")
product2 = Product("Молоко", 1.5, 5, "05.01.2022")

add_product_to_table(product1)
add_product_to_table(product2)
product_table

{'Яблоки': <__main__.Product at 0x7eb44e287730>,
 'Молоко': <__main__.Product at 0x7eb44e285330>}

Написать функцию для нахождения наиболее часто встречающегося ключа в хеш-таблице.

In [ ]:
def most_frequent_key(hash_table):
    key_count = {}
    max_count = 0
    most_frequent_key = None

    # Подсчет количества вхождений каждого ключа
    for key in hash_table:
        if key in key_count:
            key_count[key] += 1
        else:
            key_count[key] = 1

        # Обновление наиболее часто встречающегося ключа
        if key_count[key] > max_count:
            max_count = key_count[key]
            most_frequent_key = key

    return most_frequent_key

# Пример использования:
product_table = ProductHashTable()

product1 = Product("Яблоки", 2.5, 10, "01.01.2022")
product2 = Product("Молоко", 1.5, 5, "05.01.2022")
product3 = Product("Яблоки", 2.5, 10, "01.01.2022")
product4 = Product("Хлеб", 1.0, 2, "10.01.2022")

product_table.add_product(product1)
product_table.add_product(product2)
product_table.add_product(product3)
product_table.add_product(product4)

most_frequent = most_frequent_key(product_table.table)
print("Наиболее часто встречающийся ключ:", most_frequent)


Наиболее часто встречающийся ключ: Яблоки


In [ ]:
class OrderHashTable:
    def __init__(self, size):
        self.size = size
        self.table = [[] for _ in range(size)]

    def hash_function(self, key):
        return key % self.size

    def add_order(self, order):
        key = order.order_number
        index = self.hash_function(key)
        self.table[index].append(order)

    def find_order(self, order_number):
        index = self.hash_function(order_number)
        for order in self.table[index]:
            if order.order_number == order_number:
                return order
        return None

# Пример использования:
class Order:
    def __init__(self, order_number, dishes, total_cost, delivery_address):
        self.order_number = order_number
        self.dishes = dishes
        self.total_cost = total_cost
        self.delivery_address = delivery_address

order_table = OrderHashTable(10)

order1 = Order(1, ["Пицца", "Салат"], 500, "ул. Пушкина, д. 10")
order2 = Order(2, ["Суши", "Роллы"], 800, "ул. Лермонтова, д. 5")
order3 = Order(3, ["Стейк", "Картофель"], 1200, "ул. Толстого, д. 15")
order4 = Order(4, ["Суп", "Гарнир"], 400, "ул. Гоголя, д. 20")

order_table.add_order(order1)
order_table.add_order(order2)
order_table.add_order(order3)
order_table.add_order(order4)

found_order = order_table.find_order(2)
if found_order:
    print("Найден заказ:", found_order.order_number)
else:
    print("Заказ не найден")


Найден заказ: 2
